apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-hello
  namespace: argocd-hello
  labels:
    app: argocd-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-hello
  template:
    metadata:
      labels:
        app: argocd-hello
    spec:
      containers:
        - name: hello
          image: aplulu/cloud-run-hello:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: argocd-hello
  namespace: argocd-hello
spec:
  selector:
    app: argocd-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-hello
  namespace: argocd-hello
spec:
  rules:
    - host: argocd-hello.aplulu.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-hello
                port:
                  number: 8080
