apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-hello
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/aplulu/argocd-playground.git
    targetRevision: HEAD
    path: argocd-hello
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-hello
